# This is a basic workflow to help you get started with Actions

name: custom private action

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    #runs-on: linux
    name: A job to say hello
    steps:
    # To use this repository's private action,
    # you must check out the repository
    - name: Clone private repository
      uses: GuillaumeFalourd/clone-github-repo-action@v1
      with:
        owner: 'pisineen'
        repository: 'private-github-action'
        access-token: ${{ secrets.ACCESS_TOKEN }}
    - name: Validation
      run: |
        ls -lR ./private-github-action
    - name: Hello world action step
      uses: ./private-github-action # Uses an action in the root directory
      id: hello
      with:
        who-to-greet: 'piiiii'
    # Use the output from the `hello` step
    - name: Get the output time
      run: echo "The time was ${{ steps.hello.outputs.time }}"
